name: freedefense
description: tower defense game

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0"

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.12.0
  path_provider: 2.1.0
  provider: 6.0.5
  hive: 2.2.3
  hive_flutter: 1.1.0
  flutter_carousel_slider: 1.1.0
  flame_audio: 2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: 2.0.1

flutter:
  assets:
    - assets/images/weapon/
    - assets/images/enemy/
    - assets/images/neutral/
    - assets/images/
    - assets/weaponParams.json
    - assets/enemyParams.json
    - assets/spacescape/images/
    - assets/spacescape/audio/
    - assets/spacescape/fonts/BungeeInline/
    - assets/tiles/
